name: rethinkdb_driver
version: 2.2.0
author: William Welch <billywelch@gmail.com>
description: Dart driver for RethinkDB.
homepage: https://github.com/billysometimes/rethinkdb
documentation: https://github.com/billysometimes/rethinkdb
dependencies:
  protobuf: "^0.5.1+2"
